### ISSUE TITLE
DELETE /produtos/id

### ISSUE THREAD

**Issue by LDinizz** [catolicasc-social/api#13]
Criar route para DELETE/produtos/id

**Comment by murillo94** [comment]
Alterei `products` para `produtos` pelo fato de deixar os nomes em pt-BR, para ser um padrão do projeto, tanto no backend como no frontend, as rotas no caso.

**Comment by murillo94** [comment]
Fechando essa issue devido ao fato de que já há uma outra issue com o mesmo intuito que foi criada antes. No caso essa https://github.com/catolicasc-social/api/issues/5
